'use client'

import { useEffect, useState } from 'react'
import EditAgentModal from './EditAgentModal'

type Agent = {
  id: string
  name: string
  emoji: string
  domain: string
  subCategory: string
  description: string
  defaultModel: string
  systemPrompt: string
  autoGenerated: boolean
}

export default function AllAgentsView() {
  const [agents, setAgents] = useState<Agent[]>([])
  const [searchQuery, setSearchQuery] = useState('')
  const [filterDomain, setFilterDomain] = useState<string>('all')
  const [selectedAgent, setSelectedAgent] = useState<Agent | null>(null)
  const [isEditModalOpen, setIsEditModalOpen] = useState(false)

  useEffect(() => {
    // TODO: Fetch agents from API
    // Placeholder data
    setAgents([
      {
        id: '1',
        name: 'Marketing Strategist - B2B SaaS',
        emoji: '📊',
        domain: 'marketing',
        subCategory: 'strategy',
        description: 'Specialized in B2B SaaS marketing strategy and positioning',
        defaultModel: 'claude-sonnet-4',
        systemPrompt: 'You are a marketing strategist specialized in B2B SaaS...',
        autoGenerated: false
      },
      {
        id: '2',
        name: 'Code Reviewer - Python Backend',
        emoji: '🔍',
        domain: 'engineering',
        subCategory: 'backend',
        description: 'Expert code reviewer for Python backend systems',
        defaultModel: 'claude-sonnet-4',
        systemPrompt: 'You are an expert code reviewer for Python backend systems...',
        autoGenerated: false
      },
      {
        id: '3',
        name: 'Email Copywriter - Technical',
        emoji: '✍️',
        domain: 'content',
        subCategory: 'writing',
        description: 'Creates compelling technical email copy',
        defaultModel: 'gpt-4',
        systemPrompt: 'You are an email copywriter specialized in technical content...',
        autoGenerated: true
      }
    ])
  }, [])

  const handleEditAgent = (agent: Agent) => {
    setSelectedAgent(agent)
    setIsEditModalOpen(true)
  }

  const handleSaveAgent = (updatedAgent: Agent) => {
    setAgents(agents.map(a => a.id === updatedAgent.id ? updatedAgent : a))
  }

  const handleDeleteAgent = (agentId: string) => {
    setAgents(agents.filter(a => a.id !== agentId))
  }

  const filteredAgents = agents.filter(agent => {
    const matchesSearch = agent.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
                         (agent.description?.toLowerCase().includes(searchQuery.toLowerCase()) ?? false)
    const matchesDomain = filterDomain === 'all' || agent.domain === filterDomain
    return matchesSearch && matchesDomain
  })

  const getModelBadgeColor = (model: string) => {
    if (model.includes('claude')) return 'bg-burgundy text-cream'
    if (model.includes('gpt')) return 'bg-sage text-cream'
    if (model.includes('gemini')) return 'bg-gold text-espresso'
    return 'bg-charcoal text-cream'
  }

  return (
    <div>
      {/* Search and Filters */}
      <div className="mb-6 space-y-4">
        <div className="flex gap-4">
          <input
            type="text"
            placeholder="Search agents..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="flex-1 px-4 py-2.5 bg-parchment border border-light-gray rounded focus:outline-none focus:border-burgundy transition-colors"
          />
          <select
            value={filterDomain}
            onChange={(e) => setFilterDomain(e.target.value)}
            className="px-4 py-2.5 bg-parchment border border-light-gray rounded focus:outline-none focus:border-burgundy transition-colors"
          >
            <option value="all">All Domains</option>
            <option value="marketing">📊 Marketing</option>
            <option value="engineering">⚙️ Engineering</option>
            <option value="design">🎨 Design</option>
            <option value="content">✍️ Content</option>
            <option value="business">💼 Business</option>
          </select>
        </div>

        <div className="flex items-center justify-between text-sm">
          <p className="text-warm-gray">
            {filteredAgents.length} {filteredAgents.length === 1 ? 'agent' : 'agents'}
            {searchQuery && ` matching "${searchQuery}"`}
          </p>
          <div className="flex gap-2">
            <button className="px-3 py-1 text-warm-gray hover:text-burgundy transition-colors">
              Sort: A-Z
            </button>
            <button className="px-3 py-1 text-warm-gray hover:text-burgundy transition-colors">
              View: Grid
            </button>
          </div>
        </div>
      </div>

      {/* Agents Grid */}
      {filteredAgents.length === 0 ? (
        <div className="bg-parchment rounded border-2 border-dashed border-light-gray p-12 text-center">
          <div className="text-6xl mb-4">🔍</div>
          <h3 className="font-serif text-xl text-coffee mb-2">No agents found</h3>
          <p className="text-warm-gray">
            {searchQuery
              ? `No agents match "${searchQuery}"`
              : 'Create your first agent to get started'}
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredAgents.map(agent => (
            <div
              key={agent.id}
              onClick={() => handleEditAgent(agent)}
              className="bg-parchment p-5 rounded border border-light-gray hover:border-burgundy hover:shadow-lg transition-all cursor-pointer group"
            >
              {/* Agent Header */}
              <div className="flex items-start gap-3 mb-3">
                <span className="text-3xl">{agent.emoji}</span>
                <div className="flex-1 min-w-0">
                  <h3 className="font-medium text-coffee mb-1 group-hover:text-burgundy transition-colors">
                    {agent.name}
                  </h3>
                  {agent.description && (
                    <p className="text-sm text-charcoal line-clamp-2">{agent.description}</p>
                  )}
                </div>
              </div>

              {/* Agent Metadata */}
              <div className="flex flex-wrap gap-2 mt-4">
                <span className={`text-xs px-2 py-1 rounded font-medium ${getModelBadgeColor(agent.defaultModel)}`}>
                  {agent.defaultModel}
                </span>
                {agent.autoGenerated && (
                  <span className="text-xs px-2 py-1 bg-gold bg-opacity-20 text-coffee rounded font-medium">
                    ✨ Auto-generated
                  </span>
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Edit Agent Modal */}
      {selectedAgent && (
        <EditAgentModal
          isOpen={isEditModalOpen}
          onClose={() => setIsEditModalOpen(false)}
          onSave={handleSaveAgent}
          onDelete={handleDeleteAgent}
          agent={selectedAgent}
        />
      )}
    </div>
  )
}
