'use client'

import { useState, useEffect } from 'react'
import DomainView from '@/app/components/agents/DomainView'
import AllAgentsView from '@/app/components/agents/AllAgentsView'
import CreateAgentModal from '@/app/components/agents/CreateAgentModal'
import EditAgentModal from '@/app/components/agents/EditAgentModal'

type ViewType = 'domain' | 'all'

type Agent = {
  id: string
  name: string
  emoji: string
  domain: string
  subCategory: string
  description: string
  defaultModel: string
  systemPrompt: string
  autoGenerated: boolean
}

export default function AgentsPage() {
  const [activeView, setActiveView] = useState<ViewType>('domain')
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false)
  const [prefilledDomain, setPrefilledDomain] = useState<string | null>(null)
  const [agents, setAgents] = useState<Agent[]>([])
  const [selectedAgent, setSelectedAgent] = useState<Agent | null>(null)
  const [isEditModalOpen, setIsEditModalOpen] = useState(false)

  useEffect(() => {
    // TODO: Fetch from API
    setAgents([
      {
        id: '1',
        name: 'Marketing Strategist - B2B SaaS',
        emoji: '📊',
        domain: 'marketing',
        subCategory: 'strategy',
        description: 'Specialized in B2B SaaS marketing strategy and positioning',
        defaultModel: 'claude-sonnet-4',
        systemPrompt: 'You are a B2B SaaS marketing expert...',
        autoGenerated: false
      },
      {
        id: '2',
        name: 'Code Reviewer - Python Backend',
        emoji: '🔍',
        domain: 'engineering',
        subCategory: 'backend',
        description: 'Expert code reviewer for Python backend systems',
        defaultModel: 'claude-sonnet-4',
        systemPrompt: 'You are a Python backend expert...',
        autoGenerated: false
      },
      {
        id: '3',
        name: 'Email Copywriter - Technical',
        emoji: '✍️',
        domain: 'content',
        subCategory: 'writing',
        description: 'Technical email copywriting specialist',
        defaultModel: 'gpt-4',
        systemPrompt: 'You are a technical copywriter...',
        autoGenerated: false
      }
    ])
  }, [])

  const handleCreateAgent = (agentData: any) => {
    const newAgent: Agent = {
      id: Date.now().toString(),
      name: `${agentData.role} - ${agentData.specialization}`,
      emoji: agentData.emoji,
      domain: agentData.domain,
      subCategory: agentData.subCategory,
      description: agentData.description,
      defaultModel: agentData.defaultModel,
      systemPrompt: agentData.systemPrompt,
      autoGenerated: false
    }
    setAgents([...agents, newAgent])
    setPrefilledDomain(null)
    // TODO: Save to API
  }

  const handleCreateAgentInDomain = (domain: string) => {
    setPrefilledDomain(domain)
    setIsCreateModalOpen(true)
  }

  const handleEditAgentFromDomain = (agent: Agent) => {
    setSelectedAgent(agent)
    setIsEditModalOpen(true)
  }

  const handleSaveAgent = (updatedAgent: Agent) => {
    setAgents(agents.map(a => a.id === updatedAgent.id ? updatedAgent : a))
    // TODO: Save to API
  }

  const handleDeleteAgent = (agentId: string) => {
    setAgents(agents.filter(a => a.id !== agentId))
    // TODO: Delete from API
  }

  return (
    <div className="min-h-screen bg-cream">
      {/* Header */}
      <header className="bg-espresso text-cream border-b border-mocha">
        <div className="max-w-7xl mx-auto px-8 py-4">
          {/* Top Nav */}
          <div className="flex items-center justify-between mb-4">
            <a href="/" className="font-serif text-xl font-semibold hover:text-gold transition-colors">
              The.Cafe
            </a>
            <div className="flex gap-6">
              <a href="/projects" className="text-parchment hover:text-gold transition-colors">
                Projects
              </a>
              <a href="/agents" className="text-gold font-medium border-b-2 border-gold pb-1">
                Agents
              </a>
            </div>
          </div>
          {/* Page Header */}
          <div className="flex items-center justify-between">
            <div>
              <h1 className="font-serif text-3xl font-semibold mb-1">Agents</h1>
              <p className="text-parchment text-sm opacity-80">Browse and manage your AI agents</p>
            </div>
            <button
              onClick={() => setIsCreateModalOpen(true)}
              className="bg-burgundy hover:bg-coffee text-cream px-6 py-2.5 rounded transition-colors font-medium"
            >
              + New Agent
            </button>
          </div>
        </div>
      </header>

      {/* Tab Navigation */}
      <div className="bg-parchment border-b border-light-gray">
        <div className="max-w-7xl mx-auto px-8">
          <nav className="flex gap-8">
            <button
              onClick={() => setActiveView('domain')}
              className={`py-4 px-2 font-medium border-b-2 transition-colors ${
                activeView === 'domain'
                  ? 'border-burgundy text-espresso'
                  : 'border-transparent text-warm-gray hover:text-coffee'
              }`}
            >
              📁 Domain Hierarchy
            </button>
            <button
              onClick={() => setActiveView('all')}
              className={`py-4 px-2 font-medium border-b-2 transition-colors ${
                activeView === 'all'
                  ? 'border-burgundy text-espresso'
                  : 'border-transparent text-warm-gray hover:text-coffee'
              }`}
            >
              🤖 All Agents
            </button>
          </nav>
        </div>
      </div>

      {/* Content */}
      <main className="max-w-7xl mx-auto px-8 py-8">
        {activeView === 'domain' && (
          <DomainView
            agents={agents}
            onEditAgent={handleEditAgentFromDomain}
            onCreateAgentInDomain={handleCreateAgentInDomain}
          />
        )}
        {activeView === 'all' && <AllAgentsView />}
      </main>

      {/* Create Agent Modal */}
      <CreateAgentModal
        isOpen={isCreateModalOpen}
        onClose={() => {
          setIsCreateModalOpen(false)
          setPrefilledDomain(null)
        }}
        onSubmit={handleCreateAgent}
        initialDomain={prefilledDomain}
      />

      {/* Edit Agent Modal */}
      {selectedAgent && (
        <EditAgentModal
          isOpen={isEditModalOpen}
          onClose={() => setIsEditModalOpen(false)}
          onSave={handleSaveAgent}
          onDelete={handleDeleteAgent}
          agent={selectedAgent}
        />
      )}
    </div>
  )
}
